quarkus:

  # APPLICATION

  application:
    name: ludrive

  # IN REST

  http:
    port: 9080
    root-path: /api

  # IN GRPC

  grpc:
    server:
      use-separate-server: false
      port: 9090

  # OUT JPA

  datasource:

    management:
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5432/ludrive-dev
      username: ludrive-dev
      password: ludrive-dev

  hibernate-orm:

    management:
      datasource: management
      packages: app.ludrive.adapters.out.persistence.management.jpa.entity
      schema-management:
        strategy: none

  liquibase:

    management:
      change-log: db/management/managementChangeLog.xml
      migrate-at-start: false

  # TELEMETRY

  otel:
    traces:
      enabled: true
    metrics:
      enabled: true
    logs:
      enabled: true

  # DEVELOPMENT

  devservices:
    enabled: false

smallrye:
  jwt:
    sign:
      key:
        location: keys/privateKey.pem
    verify:
      key:
        location: keys/publicKey.pem
